"""Add contact fields to subchain

Revision ID: 1da6a2fe16ab
Revises: 971e441cfb38
Create Date: 2024-12-03 19:01:29.284162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da6a2fe16ab'
down_revision = '971e441cfb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subchain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('contact_person', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subchain', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('contact_person')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
