"""Add Subchain model

Revision ID: 48405027f49f
Revises: 14a57c0f6bbe
Create Date: 2024-06-09 13:21:33.847676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48405027f49f'
down_revision = '14a57c0f6bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###
