"""Initial migration

Revision ID: 84a13703dd02
Revises: 
Create Date: 2024-12-02 12:20:51.322768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a13703dd02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('return',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('supermarket_id', sa.Integer(), nullable=False),
    sa.Column('subchain_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subchain_id'], ['subchain.id'], ),
    sa.ForeignKeyConstraint(['supermarket_id'], ['supermarket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('return_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['return.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('return_item')
    op.drop_table('return')
    # ### end Alembic commands ###
