"""Add is_return field to Delivery model

Revision ID: 8edee7f47fe6
Revises: c8c7d8785261
Create Date: 2024-06-11 10:56:55.818020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8edee7f47fe6'
down_revision = 'c8c7d8785261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ...
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_return', sa.Boolean(), nullable=False, server_default='0'))
    # ...
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_column('is_return')

    # ### end Alembic commands ###
