"""Add subchain_id to Delivery

Revision ID: c8c7d8785261
Revises: 48405027f49f
Create Date: 2024-06-09 14:19:38.762935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c7d8785261'
down_revision = '48405027f49f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subchain_id', sa.Integer(), nullable=True))
        #  batch_op.create_foreign_key(None, 'subchain', ['subchain_id'], ['id'])
        batch_op.create_foreign_key('fk_delivery_subchain_id', 'subchain', ['subchain_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subchain_id')

    # ### end Alembic commands ###
