"""Add return_date to Delivery model

Revision ID: e4b894c63be8
Revises: 8edee7f47fe6
Create Date: 2024-06-16 21:23:01.671387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b894c63be8'
down_revision = '8edee7f47fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_date', sa.Date(), nullable=True))
        batch_op.alter_column('is_return',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.alter_column('is_return',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_column('return_date')

    # ### end Alembic commands ###
